import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { excludeGeneratedExtensionShims } from "../src/core/extensions/builtin/config-reload/generated-shim-filter.ts";

const roots: string[] = [];
afterEach(() => {
	for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function agentDirFixture(): string {
	const root = mkdtempSync(join(tmpdir(), "senpi-shimfilter-"));
	roots.push(root);
	mkdirSync(join(root, "extensions"), { recursive: true });
	return root;
}

const BANNER = "// Generated by senpi. Delete this file to stop loading the default global extension.\n";

describe("generated shim change filter", () => {
	describe("#given a rewritten generated global-default shim", () => {
		it("#then the path is dropped so a sibling session's rewrite cannot reload us", () => {
			const agentDir = agentDirFixture();
			const shim = join(agentDir, "extensions", "diff.js");
			writeFileSync(shim, `${BANNER}export { default } from "file:///somewhere/diff.js";\n`);

			expect(excludeGeneratedExtensionShims([shim], agentDir)).toEqual([]);
		});
	});

	describe("#given a real user extension in the same directory", () => {
		it("#then it still passes through", () => {
			const agentDir = agentDirFixture();
			const real = join(agentDir, "extensions", "mine.js");
			writeFileSync(real, "export default () => {};\n");

			expect(excludeGeneratedExtensionShims([real], agentDir)).toEqual([real]);
		});
	});

	describe("#given a user file that replaced a generated shim", () => {
		it("#then it is watched again because the banner is gone", () => {
			const agentDir = agentDirFixture();
			const replaced = join(agentDir, "extensions", "tps.js");
			writeFileSync(replaced, "export default () => { /* mine now */ };\n");

			expect(excludeGeneratedExtensionShims([replaced], agentDir)).toEqual([replaced]);
		});
	});

	describe("#given config paths outside the extensions directory", () => {
		it("#then they are never dropped", () => {
			const agentDir = agentDirFixture();
			const settings = join(agentDir, "settings.json");
			writeFileSync(settings, "{}\n");

			expect(excludeGeneratedExtensionShims([settings], agentDir)).toEqual([settings]);
		});
	});
});
